apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-system-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-rental-system
  template:
    metadata:
      labels:
        app: car-rental-system
    spec:
      containers:
        - name: car-rental-system-container
          image: supersection/rentalcarsystem:latest
          ports:
            - containerPort: 8080
